version: 3
endpoint: http://localhost:8081
admin_secret: iOiJIUzI1NiIsInR5cCeyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IlBlcGUiLCJhZG1pbiI6dHJ1ZSwia
metadata_directory: metadata
migrations_directory: migrations
actions:
  kind: synchronous
  # handler_webhook_baseurl: http://localhost:3000